/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChat: typeof import('./src/components/AIChat.vue')['default']
    ICarbonArrowDown: typeof import('~icons/carbon/arrow-down')['default']
    ICarbonCopy: typeof import('~icons/carbon/copy')['default']
    ICarbonFolder: typeof import('~icons/carbon/folder')['default']
    ICarbonPlay: typeof import('~icons/carbon/play')['default']
    ICarbonReset: typeof import('~icons/carbon/reset')['default']
    ICarbonSettings: typeof import('~icons/carbon/settings')['default']
    ICarbonStop: typeof import('~icons/carbon/stop')['default']
    ICarbonTemplate: typeof import('~icons/carbon/template')['default']
    ICarbonTerminal: typeof import('~icons/carbon/terminal')['default']
    ICarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    ICarbonUpload: typeof import('~icons/carbon/upload')['default']
    ILogosFfmpeg: typeof import('~icons/logos/ffmpeg')['default']
    LogsCard: typeof import('./src/components/LogsCard.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCode: typeof import('naive-ui')['NCode']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NThing: typeof import('naive-ui')['NThing']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Options: typeof import('./src/components/Options.vue')['default']
    PresetSelector: typeof import('./src/components/PresetSelector.vue')['default']
    Works: typeof import('./src/components/Works.vue')['default']
  }
}
