// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['app']['App']['ExecuteCommand'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['app']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2);
}

export function StopCommand() {
  return window['go']['app']['App']['StopCommand']();
}
